/// <reference types="@cloudflare/workers-types" />

// @ts-expect-error The OpenNext Worker is generated by `npm run cf:build`.
import openNextHandler from "./.open-next/worker.js";

import { handleDailySchedule } from "./src/cloudflare/daily-scheduler";

export default {
  fetch: openNextHandler.fetch,
  async scheduled(controller, env) {
    await handleDailySchedule(controller, env);
  }
} satisfies ExportedHandler<CloudflareEnv>;
